object Dependencies {
    const val ANDROIDX_CORE_KTX = "androidx.core:core-ktx:${DependenciesVersions.CORE_KTX}"
    const val ANDROIDX_APPCOMPAT = "androidx.appcompat:appcompat:${DependenciesVersions.APPCOMPAT}"
    const val MATERIAL = "com.google.android.material:material:${DependenciesVersions.MATERIAL}"
    const val CONSTRAINTLAYOUT = "androidx.constraintlayout:constraintlayout:${DependenciesVersions.CONSTRAINTLAYOUT}"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx:${DependenciesVersions.NAVIGATION}"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx:${DependenciesVersions.NAVIGATION}"
    const val HILT_COMPILER = "com.google.dagger:hilt-compiler:${DependenciesVersions.HILT}"
    const val HILT_ANDROID = "com.google.dagger:hilt-android:${DependenciesVersions.HILT}"
    const val ROOM  = "androidx.room:room-runtime:${DependenciesVersions.ROOM}"
    const val ROOM_KTX  = "androidx.room:room-ktx:${DependenciesVersions.ROOM}"
    const val ROOM_COMPILER  = "androidx.room:room-compiler:${DependenciesVersions.ROOM}"
    const val PLAY_SERVICES_MAPS = "com.google.android.gms:play-services-maps:${DependenciesVersions.PLAY_SERVICES}"
    const val PLAY_SERVICES_LOCATION = "com.google.android.gms:play-services-location:${DependenciesVersions.PLAY_SERVICES}"
    const val GOOGLE_MAP_UTIL = "com.google.maps.android:android-maps-utils:${DependenciesVersions.MAP_UTIL}"
    const val COROUTINES_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${DependenciesVersions.COROUTINES}"
    const val COROUTINES_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${DependenciesVersions.COROUTINES}"
    const val INDICATOR = "me.relex:circleindicator:${DependenciesVersions.INDICATOR}"
}
